import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const profiles = sqliteTable('profiles', { id: text('id').primaryKey(), email: text('email').notNull().unique(), role: text('role').notNull().default('admin'), createdAt: text('created_at').notNull() });
export const findItems = sqliteTable('find_items', { id: text('id').primaryKey(), brand: text('brand').notNull(), name: text('name').notNull(), category: text('category'), description: text('description'), price: text('price'), sizes: text('sizes', { mode: 'json' }).$type<string[]>(), color: text('color'), status: text('status').notNull().default('check'), published: integer('published', { mode: 'boolean' }).notNull().default(false), sortOrder: integer('sort_order').notNull().default(0), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() });
export const findItemImages = sqliteTable('find_item_images', { id: text('id').primaryKey(), findItemId: text('find_item_id').notNull().references(() => findItems.id, { onDelete: 'cascade' }), storageKey: text('storage_key').notNull(), url: text('url').notNull(), alt: text('alt'), sortOrder: integer('sort_order').notNull().default(0), isCover: integer('is_cover', { mode: 'boolean' }).notNull().default(false) });
export const requests = sqliteTable('requests', { id: text('id').primaryKey(), customerName: text('customer_name').notNull(), contact: text('contact').notNull(), source: text('source').notNull().default('website'), requestedItem: text('requested_item'), link: text('link'), brand: text('brand'), size: text('size'), color: text('color'), imageKey: text('image_key'), message: text('message'), preferredContact: text('preferred_contact').notNull().default('telegram'), status: text('status').notNull().default('new'), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() });
export const reviews = sqliteTable('reviews', { id: text('id').primaryKey(), imageKey: text('image_key'), imageUrl: text('image_url'), additionalImages: text('additional_images', { mode: 'json' }).$type<string[]>(), text: text('text').notNull(), customerName: text('customer_name'), date: text('date'), type: text('type').notNull().default('review'), published: integer('published', { mode: 'boolean' }).notNull().default(false), sortOrder: integer('sort_order').notNull().default(0), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() });
export const siteSettings = sqliteTable('site_settings', { key: text('key').primaryKey(), value: text('value').notNull(), updatedAt: text('updated_at').notNull() });
export const brands = sqliteTable('brands', { id: text('id').primaryKey(), name: text('name').notNull().unique(), sortOrder: integer('sort_order').notNull().default(0), published: integer('published', { mode: 'boolean' }).notNull().default(true) });
export const aboutContent = sqliteTable('about_content', { key: text('key').primaryKey(), title: text('title').notNull(), body: text('body').notNull(), sortOrder: integer('sort_order').notNull().default(0), updatedAt: text('updated_at').notNull() });
